cloud-bastion
Otus-DevOps-2018-05/zombrox_infra pull request #2
Opened 2018-06-26 22:57 UTC by zombrox

# Выполнено ДЗ № 3

 - [*] Основное ДЗ
 - [*] Задание со *

## В процессе сделано:
 - Созданы 2 VM в CGP (1-на с внешним IP 2-я без)
 - настроено Agent Forwarding 
 - в локальных ~/.ssh/config и ~/.bashrc произведены соотвествующие настройки для подключения к someinternal host одной командой из одно слова someinternalhost (см. README.md)
 - на bastion установлен VPN сервер pritunl

## Как проверить работоспособность:
 - я ХЗ как это проверить т.к. pritunl запускается исключительно на IPv6 интерфейсе, попытки отключить IPv6 через sysctl и grub не помогли, а нормального конфига, что бы там явно указать на каком интерфейсе висеть, у pritunl нет.

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [*] Выставил label с темой домашнего задания

2018-06-29 07:06 UTC, chromko requested changes
Можешь заставить пройти автотесты? Судя по ним тревис даже не подключился к впну

2018-06-29 07:06 UTC, chromko commented on README.md
> +echo -e "\nHost bastion\nHostname 35.206.171.215\nPort 22\nUser appuser\nIdentityFile ~/.ssh/appuser\nForwardAgent yes\n" >> ~/.ssh/config
Это, конечно, то еще наказание читать такой код)
лучше делать что-то вроде 
cat << EOF filename
содержимое файла
...
EOF

2018-06-29 07:06 UTC, chromko commented on README.md
> +echo "alias someinternalhost='ssh someinternalhost'" >> ~/.bashrc
не, ну одним словом это уже даже перебор =)
Хотя по содержанию ~/.ssh/config нет вопросов

2018-06-30 15:47 UTC, zombrox commented on README.md
> +echo -e "\nHost bastion\nHostname 35.206.171.215\nPort 22\nUser appuser\nIdentityFile ~/.ssh/appuser\nForwardAgent yes\n" >> ~/.ssh/config
Изменил README.md  в соотвествии с пожеланиями.

2018-06-30 15:48 UTC, zombrox commented on README.md
> +echo "alias someinternalhost='ssh someinternalhost'" >> ~/.bashrc
Ну и это тоже соответственно поменял.

2018-06-30 15:49 UTC, zombrox commented
Автотесты теперь проходят. Нашел как починить IPv4.

2018-06-30 15:50 UTC, chromko approved these changes
Теперь все хорошо. Претензий нет.

2018-06-30 16:02 UTC, merged